name = "rsbench-pastebin"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-20"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "rsbench"
database_name = "rsbench"
database_id = "4bee5df6-439c-4e14-ba92-fefb12a01818"
