name = "rsbench-pastebin"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-20"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "rsbench"
database_name = "rsbench"
database_id = "00b34222-9056-4b96-b1f8-5de1f309f288"
